### PR TITLE
GUI for online detector from live RGBD video sequence

### PR DESCRIPTION
**Pull request by ssheorey**
Online 3D object detection pipeline.

-  Connects to a RGBD camera or RGBD video file (currently RealSense camera and bag file format are supported).
-  Captures / reads color and depth frames.
-  Convert frames to point cloud.
-  Run PointPillars object detector (Tensorflow or PyTorch) on point cloud.
-  Visualize point cloud video and results.

Closes https://github.com/intel-isl/Open3D/issues/2705 
Also this is a similar request: https://github.com/intel-isl/Open3D/issues/2580

This PR depends on: 
- [X] https://github.com/intel-isl/Open3D/pull/3113
- [ ] https://github.com/intel-isl/Open3D/pull/3002

With detected bounding box and score threshold slider:
image

Bird's eye view (ROSbag file)
Screenshot 2021-03-13 at 12 12 09 PM

Camera View  (ROSbag file)
Screenshot 2021-03-13 at 12 11 57 PM

Live camera
Screenshot 2021-03-12 at 3 32 55 PM

Live camera
Screenshot 2021-03-12 at 3 33 10 PM

Future PRs:
- PointPillars + ScanNet trained model

---
This change is [Reviewable](https://reviewable.io/reviews/intel-isl/open3d-ml/239)

### CODE REVIEW

**Review by prewettg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d-ml/239)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @germanros1987, @Prantl, @ssheorey, and @theNded)

___
*[ml3d/online/detector.py, line 74 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/239#-MVhTbycDvcTipbxOmN6:-MVhTbycDvcTipbxOmN7:bxcwdym) ([raw file](https://github.com/intel-isl/open3d-ml/blob/73ae8373583cd8a5d2e280c0cd9a9865e98e7a58/ml3d/online/detector.py#L74)):*
> ```Python
>         self.material = o3d.visualization.rendering.Material()
>         self.material.shader = "defaultLit"
>         self.material.point_size = 8
> ```

You might want to multiply by `self.window.scaling`, otherwise the size of the points may potentially be different on macOS and Linux.
___
*[ml3d/online/detector.py, line 80 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/239#-MVhUNR2EkgpX0uMHHFd:-MVhUNR2EkgpX0uMHHFe:bt7j8sv) ([raw file](https://github.com/intel-isl/open3d-ml/blob/73ae8373583cd8a5d2e280c0cd9a9865e98e7a58/ml3d/online/detector.py#L80)):*
> ```Python
>         self.window = gui.Application.instance.create_window(
>             "Open3D || 3D Object Detection", 1024, 768)
>         self.window.set_on_layout(self._on_layout)  # Window resize callback
> ```

Regarding the comment: strictly speaking, this is the *layout* callback, not the resize callback. It is called on resize, but it can also be called in other situations.
___
*[ml3d/online/detector.py, line 89 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/239#-MVhVFWA62zKgRwbkrvR:-MVhVFWA62zKgRwbkrvS:b-7va14q) ([raw file](https://github.com/intel-isl/open3d-ml/blob/73ae8373583cd8a5d2e280c0cd9a9865e98e7a58/ml3d/online/detector.py#L89)):*
> ```Python
>             True)  # makes UI _much_ more responsive
>         self.pcdview.scene = rendering.Open3DScene(self.window.renderer)
>         self.pcdview.scene.set_background([1, 1, 1, 1])  # White brackground
> ```

Typo, "background" not "brackground"

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d-ml/239)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @germanros1987, @Prantl, @prewettg, and @theNded)

___
*[ml3d/online/detector.py, line 74 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/239#-MVhTbycDvcTipbxOmN6:-MVwqglT3M6dxa-3OO0d:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/73ae8373583cd8a5d2e280c0cd9a9865e98e7a58/ml3d/online/detector.py#L74)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

You might want to multiply by `self.window.scaling`, otherwise the size of the points may potentially be different on macOS and Linux.
</blockquote></details>

Done.
___
*[ml3d/online/detector.py, line 80 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/239#-MVhUNR2EkgpX0uMHHFd:-MVwqivMEX_ObYd5mB9-:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/73ae8373583cd8a5d2e280c0cd9a9865e98e7a58/ml3d/online/detector.py#L80)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

Regarding the comment: strictly speaking, this is the *layout* callback, not the resize callback. It is called on resize, but it can also be called in other situations.
</blockquote></details>

Done.
___
*[ml3d/online/detector.py, line 89 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/239#-MVhVFWA62zKgRwbkrvR:-MVwqk7K7R7srPTjWC4F:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/73ae8373583cd8a5d2e280c0cd9a9865e98e7a58/ml3d/online/detector.py#L89)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

Typo, "background" not "brackground"
</blockquote></details>

Done.

**Comment by theNded** [comment]
Just a general question, can we simultaneously display capture and 3D view in the same window? Now it seems only toggling is supported.

**Comment by ssheorey** [comment]
> Just a general question, can we simultaneously display capture and 3D view in the same window? Now it seems only toggling is supported.

Yes, @germanros1987 requested that as well. I can add that as soon as this PR https://github.com/intel-isl/Open3D/pull/3002 for a VideoWidget is merged.

**Comment by ssheorey** [comment]
Updated panel with color and depth image previews. Previews can be hidden.

image

**Pull request closed without merging**
